
# C++ Support
CONFIG_CPP=y
CONFIG_STD_CPP20=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_NEWLIB_LIBC=y
# FPU Support
CONFIG_FPU=y
CONFIG_FPU_SHARING=y

# ESP32-S3 PSRAM - Use PSRAM for large allocations!
CONFIG_ESP_SPIRAM=y
CONFIG_SPIRAM_MODE_OCT=y
CONFIG_ESP_SPIRAM_HEAP_SIZE=4194304

# Memory - Optimized for DRAM
CONFIG_HEAP_MEM_POOL_SIZE=65536
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_IDLE_STACK_SIZE=2048
CONFIG_ISR_STACK_SIZE=4096

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# GPIO
CONFIG_GPIO=y

# I2S
CONFIG_I2S=y
CONFIG_I2S_ESP32=y
CONFIG_I2S_ESP32_RX_BLOCK_COUNT=16
CONFIG_DMA=y
CONFIG_DMA_ESP32=y

# Ring buffer
CONFIG_RING_BUFFER_LARGE=y

# Disable unnecessary features to save RAM
CONFIG_DEBUG_THREAD_INFO=n
CONFIG_THREAD_STACK_INFO=n
CONFIG_STACK_SENTINEL=n

# Speed Optimizations (Compile with -O2)
CONFIG_SPEED_OPTIMIZATIONS=y

# Disable Bluetooth to maximize free RAM & CPU performance
CONFIG_BT=n

# CPU Clock Frequency (240 MHz Max Speed)
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=240000000